### PR TITLE
Update for OCTGN 3.4

### PR DESCRIPTION
**Pull request by canisinhorto**
Just a little grooming to work with the latest version of OCTGN :)

### CODE REVIEW

**Comment by db0** [comment]
Thanks for the merge, but I'm not really maintaining this project anymore

**Comment by canisinhorto** [comment]
Ok thx. maybe you dont have to merge the readme.md. mine was just linking
to to your github repo.

Le lun. 20 déc. 2021 à 10:19, Divided by Zer0 ***@***.***> a
écrit :

**Comment by db0** [comment]
Ah too late now. Can you push an update to fix?

**Comment by canisinhorto** [comment]
Sure,  done !

Le lun. 20 déc. 2021 à 22:08, Divided by Zer0 ***@***.***> a
écrit :

**Comment by db0** [comment]
BTW, if you want to take over maintenance for this project, do contact brine in the OCTGN discord. He'll give you access to upload your version. Simply pushing your changes to my repo is not enough

**Comment by canisinhorto** [comment]
It's already done ;)

Le mar. 21 déc. 2021 à 13:05, Divided by Zer0 ***@***.***> a
écrit :

**Pull request merged**
